services:
    club_extra.tools:
        class: Club\FormExtraBundle\Helper\Tools
        arguments: [@service_container]
    club_extra.user:
        class: Club\FormExtraBundle\Helper\User
        arguments: [@service_container]
    club_extra.storage:
        class: Club\FormExtraBundle\Helper\Storage
    club_extra.flash:
        class: Club\FormExtraBundle\Helper\FlashHelper
        arguments: [@session, @translator, @logger]
